#!/bin/bash
set -e
set -x

# --- Configuration from environment (with defaults) ---
MOODLE_WWWROOT="${MOODLE_WWWROOT:-http://127.0.0.1}"
MOODLE_LANG="${MOODLE_LANG:-fr}"
MOODLE_DATAROOT="${MOODLE_DATAROOT:-/data/moodledata}"
MOODLE_DBTYPE="${MOODLE_DBTYPE:-pgsql}"
MOODLE_DBHOST="${MOODLE_DBHOST:-postgres}"
MOODLE_DBNAME="${MOODLE_DBNAME:-moodle}"
MOODLE_DBUSER="${MOODLE_DBUSER:-moodleadmin}"
MOODLE_DBPASS="${MOODLE_DBPASS:-moodlepass}"
MOODLE_DBPREFIX="${MOODLE_DBPREFIX:-mdl_}"
MOODLE_ADMINUSER="${MOODLE_ADMINUSER:-moodle}"
MOODLE_ADMINPASS="${MOODLE_ADMINPASS:-moodlepass}"
MOODLE_ADMINEMAIL="${MOODLE_ADMINEMAIL:-admin@moodle.com}"
MOODLE_SUPPORTEMAIL="${MOODLE_SUPPORTEMAIL:-support@moodle.com}"
MOODLE_FULLNAME="${MOODLE_FULLNAME:-Moodle}"
MOODLE_SHORTNAME="${MOODLE_SHORTNAME:-Moodle}"
MOODLE_SSLPROXY="${MOODLE_SSLPROXY:-false}"

CONFIG_FILE="/var/www/html/moodle/config.php"
MOODLE_CLI="/var/www/html/moodle/admin/cli"

# Create Moodle data directory with proper permissions
mkdir -p /data/moodledata && \
chown -R root:www-data /data/moodledata && \
chmod -R 0775 /data/moodledata

# Configure Apache to use 'localhost' as ServerName
echo ServerName localhost >> /etc/apache2/apache2.conf

# Remove any existing symlink to moodle_listeners.conf
rm -f /etc/apache2/sites-enabled/moodle_listeners.conf

echo "=== MoPgR Setup ==="

# =========================================================================
# GENERATE config.php FROM ENVIRONMENT
# ------------------------------------------------------------------------
# config.php is a generated artifact: it is rebuilt from environment
# variables at every container start. This makes container recreation
# safe (the file lives in the ephemeral container layer, while the
# database and moodledata are persisted as bind mounts).
# Do not edit config.php manually: use the MOODLE_* environment variables.
# ------------------------------------------------------------------------

cat > "$CONFIG_FILE" <<EOF
<?php  // Moodle configuration file, generated by MoPgR setup.sh from environment variables

unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${MOODLE_DBTYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DBHOST}';
\$CFG->dbname    = '${MOODLE_DBNAME}';
\$CFG->dbuser    = '${MOODLE_DBUSER}';
\$CFG->dbpass    = '${MOODLE_DBPASS}';
\$CFG->prefix    = '${MOODLE_DBPREFIX}';
\$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '',
  'dbsocket' => '',
);

\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${MOODLE_DATAROOT}';
\$CFG->admin     = 'admin';

\$CFG->directorypermissions = 02777;

require_once(__DIR__ . '/lib/setup.php');

// There is no php closing tag in this file,
// it is intentional because it prevents trailing whitespace problems!
EOF

if [ "${MOODLE_SSLPROXY}" = "true" ]; then
    echo "\$CFG->sslproxy = true;" >> "$CONFIG_FILE"
fi
echo "\$CFG->routerconfigured = true;" >> "$CONFIG_FILE"

chown root:www-data "$CONFIG_FILE"
chmod 0775 "$CONFIG_FILE"

# =========================================================================
# INSTALL OR UPGRADE (idempotent)
# ------------------------------------------------------------------------
# upgrade.php succeeds when the database is already installed (and is a
# no-op when nothing changed). It fails when the database is empty, in
# which case install_database.php performs the first-time installation
# (tables + admin account) using the config.php generated above.
# ------------------------------------------------------------------------

if php ${MOODLE_CLI}/upgrade.php --non-interactive; then
    echo "Moodle database is installed and up to date."
else
    echo "Moodle database is empty — running first-time installation..."
    php ${MOODLE_CLI}/install_database.php \
      --agree-license \
      --lang="${MOODLE_LANG}" \
      --adminuser="${MOODLE_ADMINUSER}" \
      --adminpass="${MOODLE_ADMINPASS}" \
      --adminemail="${MOODLE_ADMINEMAIL}" \
      --supportemail="${MOODLE_SUPPORTEMAIL}" \
      --fullname="${MOODLE_FULLNAME}" \
      --shortname="${MOODLE_SHORTNAME}"
fi

echo "Moodle setup complete."

# --------------- CRON & CRON-LOGS ---------------
mkdir -p /var/log/moodle
touch /var/log/moodle/cron.log
chown www-data:www-data /var/log/moodle/cron.log

# Write once (overwrite) to /etc/cron.d/moodle - cron.php + adhoc_task.php
cat > /etc/cron.d/moodle << 'EOF'
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/cron.php >> /var/log/moodle/cron.log 2>&1
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/cron.php >> /var/log/moodle/cron.log 2>&1
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/cron.php >> /var/log/moodle/cron.log 2>&1
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/adhoc_task.php --execute --keep-alive=59 >> /var/log/moodle/cron.log 2>&1
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/adhoc_task.php --execute --keep-alive=59 >> /var/log/moodle/cron.log 2>&1
* * * * * www-data /usr/local/bin/php /var/www/html/moodle/admin/cli/adhoc_task.php --execute --keep-alive=59 >> /var/log/moodle/cron.log 2>&1

EOF

# Start cron in the background
cron &
